import type { SlideTheme } from "@/lib/types";

export const SLIDE_THEME_PRESETS: SlideTheme[] = [
  {
    presetId: "corp-default",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Aptos Display",
      bodyFontFamily: "Aptos",
      backgroundColor: "#F7F4EE",
      textColor: "#1F2937",
      accentColor: "#C2410C",
      headerText: "Doc Forge",
      footerText: "Generated by Doc Forge",
      logoAssetPath: "",
    },
  },
  {
    presetId: "midnight-boardroom",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Aptos Display",
      bodyFontFamily: "Aptos",
      backgroundColor: "#0F172A",
      textColor: "#E2E8F0",
      accentColor: "#38BDF8",
      headerText: "Board Review",
      footerText: "Confidential",
      logoAssetPath: "",
    },
  },
  {
    presetId: "fresh-paper",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Georgia",
      bodyFontFamily: "Aptos",
      backgroundColor: "#FFFDF7",
      textColor: "#2B2B2B",
      accentColor: "#15803D",
      headerText: "Strategy Draft",
      footerText: "Prepared with Doc Forge",
      logoAssetPath: "",
    },
  },
  {
    presetId: "tech-minimal",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Aptos Display",
      bodyFontFamily: "Aptos",
      backgroundColor: "#1C1C1E",
      textColor: "#F5F5F7",
      accentColor: "#00C853",
      headerText: "Tech Briefing",
      footerText: "Internal Use Only",
      logoAssetPath: "",
    },
  },
  {
    presetId: "warm-business",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Georgia",
      bodyFontFamily: "Georgia",
      backgroundColor: "#FDF6EC",
      textColor: "#2C2C2C",
      accentColor: "#E8650A",
      headerText: "Business Review",
      footerText: "Prepared with Doc Forge",
      logoAssetPath: "",
    },
  },
  {
    presetId: "ocean-professional",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Aptos Display",
      bodyFontFamily: "Aptos",
      backgroundColor: "#0C2340",
      textColor: "#FFFFFF",
      accentColor: "#00A8E0",
      headerText: "Executive Report",
      footerText: "Confidential",
      logoAssetPath: "",
    },
  },
  {
    presetId: "pastel-workshop",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Aptos Display",
      bodyFontFamily: "Aptos",
      backgroundColor: "#F3F0FF",
      textColor: "#2D1B69",
      accentColor: "#7C3AED",
      headerText: "Workshop",
      footerText: "Prepared with Doc Forge",
      logoAssetPath: "",
    },
  },
  {
    presetId: "monochrome-print",
    tokens: {
      pageSize: "LAYOUT_WIDE",
      titleFontFamily: "Georgia",
      bodyFontFamily: "Aptos",
      backgroundColor: "#FFFFFF",
      textColor: "#000000",
      accentColor: "#666666",
      headerText: "",
      footerText: "",
      logoAssetPath: "",
    },
  },
];

export function getSlideThemePreset(presetId: string): SlideTheme | null {
  return (
    SLIDE_THEME_PRESETS.find((preset) => preset.presetId === presetId) ?? null
  );
}

export function getDefaultSlideTheme(): SlideTheme {
  return structuredClone(SLIDE_THEME_PRESETS[0]);
}
